config/routes.rb
Rails.application.routes.draw do

  root "movies#index"
  
  resources :genres

  resources :users
  get "signup" => "users#new"

  

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy] # generate only the needed routes
  end
  get "movies/filter/:filter" => "movies#index", as: :filter_movies

  get "signin" => "sessions#new"
  resource :session, only:[:create, :new, :destroy]


end

# can access routes through the browser: localhost:3000/rails/info/routes
# can access routes through rails console: rails routes

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>Copyright <%= Time.now.year %></p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo.png"), root_path%>
    <ul class="left">
      <li>
        <%= link_to "Released", movies_path%>
      </li>
      <li>
        <%= link_to "Recent Movies", filter_movies_path(:recent)%>
      </li>
      <li>
        <%= link_to "Upcoming Movies", filter_movies_path(:upcoming)%>
      </li>
      <li>
        <%= link_to "Hit Movies", filter_movies_path(:hits)%>
      </li>
      <li>
        <%= link_to "Flop Movies", filter_movies_path(:flops)%>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Account Settings", edit_user_path(current_user), class: "button"%>
        </li>
        <li>
          <%= link_to "Sign Out", session_path, method: :delete, class: "button "%>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", signin_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="content">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>